services:
  nethermind:
    image: nethermind/nethermind:latest-chiseled[
    container_name: volta-test
    command: --config=volta --data-dir=/nethermind/data_dir --JsonRpc.Host=0.0.0.0 --JsonRpc.Port=8545
    ports:
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - type: bind
        source: /data-dir # Make sure to create this dir with full access to anyone
        target: /nethermind/data_dir
    networks:
      - my-network
  barbosa:
    build: .  # Build the image from the current directory
    container_name: test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount the Docker socket

networks:
  my-network: